# Site settings
title: Izaac Log
email: jorge.izaac@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Life, Gaming, Food, Computers and Travel.
  Izaac Zavaleta
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "https://www.izaac.me" # the base hostname & protocol for your site
twitter_username: izaacze
github_username:  izaac
gems: [jekyll-paginate]
paginate: 15

# Build settings
markdown: kramdown
